module.exports = {
  GLOBAL__FIELD_ALREADY_TAKEN: 'GLOBAL__FIELD_ALREADY_TAKEN',
  GLOBAL__NOT_FOUND: 'GLOBAL__NOT_FOUND',
  CLIENT__DELETE__NOT_FOUND: 'CLIENT__DELETE__NOT_FOUND',
  CLIENT__UPDATE__NOT_FOUND: 'CLIENT__UPDATE__NOT_FOUND',
};
