module.exports = {
    GLOBAL__FIELD_ALREADY_TAKEN : 'GLOBAL__FIELD_ALREADY_TAKEN',
    GLOBAL__NOT_FOUND           : 'GLOBAL__NOT_FOUND',

    // MODULE INTERNAL CODE
    CLIENT__NOT_FOUND              : 'CLIENT__NOT_FOUND',
    CLIENT_GOAL__CLOSE__NOT_FOUND  : 'CLIENT_GOAL__CLOSE__NOT_FOUND',
    CLIENT_GOAL__DELETE__NOT_FOUND : 'CLIENT_GOAL__DELETE__NOT_FOUND',
    CLIENT_GOAL__UPDATE__NOT_FOUND : 'CLIENT_GOAL__UPDATE__NOT_FOUND',
    CLIENT_GOAL__EXISTS_ONE_ACTIVE : 'CLIENT_GOAL__EXISTS_ONE_ACTIVE',
    PLAN__NOT_FOUND                : 'PLAN__NOT_FOUND',
    PLAN__DELETE__NOT_FOUND        : 'PLAN__DELETE__NOT_FOUND',
    PLAN__UPDATE__NOT_FOUND        : 'PLAN__UPDATE__NOT_FOUND',
    TRACKING__DELETE__NOT_FOUND    : 'TRACKING__DELETE__NOT_FOUND',
    TRACKING__UPDATE__NOT_FOUND    : 'TRACKING__UPDATE__NOT_FOUND',
    CLIENT__DELETE__NOT_FOUND      : 'CLIENT__DELETE__NOT_FOUND',
    CLIENT__UPDATE__NOT_FOUND      : 'CLIENT__UPDATE__NOT_FOUND',
    AUTH__INVALID_CREDENTIALS      : 'AUTH__INVALID_CREDENTIALS',
    AUTH__USER_NOT_FOUND           : 'AUTH__USER_NOT_FOUND',
    AUTH__PASSWORD_RESET_FAILED    : 'AUTH__PASSWORD_RESET_FAILED',
    AUTH__LOWER_LICENSEE           : 'AUTH__LOWER_LICENSEE',
    AUTH__INACTIVE_ACCOUNT         : 'AUTH__INACTIVE_ACCOUNT',
}
