module.exports = {
  GLOBAL__FIELD_ALREADY_TAKEN: 'GLOBAL__FIELD_ALREADY_TAKEN',
  GLOBAL__NOT_FOUND: 'GLOBAL__NOT_FOUND',

  // MODULE INTERNAL CODE
  TRACKING__DELETE__NOT_FOUND: 'TRACKING__DELETE__NOT_FOUND',
  TRACKING__UPDATE__NOT_FOUND: 'TRACKING__UPDATE__NOT_FOUND',
  CLIENT__DELETE__NOT_FOUND: 'CLIENT__DELETE__NOT_FOUND',
  CLIENT__UPDATE__NOT_FOUND: 'CLIENT__UPDATE__NOT_FOUND',
  AUTH__INVALID_CREDENTIALS: 'AUTH__INVALID_CREDENTIALS',
  AUTH__USER_NOT_FOUND: 'AUTH__USER_NOT_FOUND',
  AUTH__PASSWORD_RESET_FAILED: 'AUTH__PASSWORD_RESET_FAILED',
};
