name: CI/CD Pipeline - Testing

on:
  push:
    tags: [deploy]
    branches: ["release/*"]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      ENVIRONMENT: testing
    secrets: inherit

  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    needs: build
    with:
      ENVIRONMENT: testing
    secrets: inherit
